export const countries = [
  { key: "afghanistan", label: "Afghanistan" },
  { key: "albania", label: "Albania" },
  { key: "algeria", label: "Algeria" },
  { key: "andorra", label: "Andorra" },
  { key: "angola", label: "Angola" },
  { key: "antigua and barbuda", label: "Antigua and Barbuda" },
  { key: "argentina", label: "Argentina" },
  { key: "armenia", label: "Armenia" },
  { key: "australia", label: "Australia" },
  { key: "austria", label: "Austria" },
  { key: "azerbaijan", label: "Azerbaijan" },
  { key: "bahamas", label: "Bahamas" },
  { key: "bahrain", label: "Bahrain" },
  { key: "bangladesh", label: "Bangladesh" },
  { key: "barbados", label: "Barbados" },
  { key: "belarus", label: "Belarus" },
  { key: "belgium", label: "Belgium" },
  { key: "belize", label: "Belize" },
  { key: "benin", label: "Benin" },
  { key: "bhutan", label: "Bhutan" },
  { key: "bolivia", label: "Bolivia" },
  { key: "botswana", label: "Botswana" },
  { key: "brazil", label: "Brazil" },
  { key: "brunei", label: "Brunei" },
  { key: "bulgaria", label: "Bulgaria" },
  { key: "burkina faso", label: "Burkina Faso" },
  { key: "burundi", label: "Burundi" },
  { key: "cabo verde", label: "Cabo Verde" },
  { key: "cambodia", label: "Cambodia" },
  { key: "cameroon", label: "Cameroon" },
  { key: "canada", label: "Canada" },
  { key: "central african republic", label: "Central African Republic" },
  { key: "chad", label: "Chad" },
  { key: "chile", label: "Chile" },
  { key: "china", label: "China" },
  { key: "colombia", label: "Colombia" },
  { key: "comoros", label: "Comoros" },
  {
    key: "congo, democratic republic of the",
    label: "Congo, Democratic Republic of the",
  },
  { key: "costa rica", label: "Costa Rica" },
  { key: "croatia", label: "Croatia" },
  { key: "cuba", label: "Cuba" },
  { key: "cyprus", label: "Cyprus" },
  { key: "czech republic", label: "Czech Republic" },
  { key: "denmark", label: "Denmark" },
  { key: "djibouti", label: "Djibouti" },
  { key: "dominica", label: "Dominica" },
  { key: "dominican republic", label: "Dominican Republic" },
  { key: "ecuador", label: "Ecuador" },
  { key: "egypt", label: "Egypt" },
  { key: "el salvador", label: "El Salvador" },
  { key: "equatorial guinea", label: "Equatorial Guinea" },
  { key: "eritrea", label: "Eritrea" },
  { key: "estonia", label: "Estonia" },
  { key: "eswatini", label: "Eswatini" },
  { key: "ethiopia", label: "Ethiopia" },
  { key: "fiji", label: "Fiji" },
  { key: "finland", label: "Finland" },
  { key: "france", label: "France" },
  { key: "gabon", label: "Gabon" },
  { key: "gambia", label: "Gambia" },
  { key: "georgia", label: "Georgia" },
  { key: "germany", label: "Germany" },
  { key: "ghana", label: "Ghana" },
  { key: "greece", label: "Greece" },
  { key: "grenada", label: "Grenada" },
  { key: "guatemala", label: "Guatemala" },
  { key: "guinea", label: "Guinea" },
  { key: "guinea-bissau", label: "Guinea-Bissau" },
  { key: "guyana", label: "Guyana" },
  { key: "haiti", label: "Haiti" },
  { key: "honduras", label: "Honduras" },
  { key: "hungary", label: "Hungary" },
  { key: "iceland", label: "Iceland" },
  { key: "india", label: "India" },
  { key: "indonesia", label: "Indonesia" },
  { key: "iran", label: "Iran" },
  { key: "iraq", label: "Iraq" },
  { key: "ireland", label: "Ireland" },
  { key: "israel", label: "Israel" },
  { key: "italy", label: "Italy" },
  { key: "jamaica", label: "Jamaica" },
  { key: "japan", label: "Japan" },
  { key: "jordan", label: "Jordan" },
  { key: "kazakhstan", label: "Kazakhstan" },
  { key: "kenya", label: "Kenya" },
  { key: "kiribati", label: "Kiribati" },
  { key: "korea, north", label: "North Korea" },
  { key: "korea, south", label: "South Korea" },
  { key: "kosovo", label: "Kosovo" },
  { key: "kuwait", label: "Kuwait" },
  { key: "kyrgyzstan", label: "Kyrgyzstan" },
  { key: "laos", label: "Laos" },
  { key: "latvia", label: "Latvia" },
  { key: "lebanon", label: "Lebanon" },
  { key: "lesotho", label: "Lesotho" },
  { key: "liberia", label: "Liberia" },
  { key: "libya", label: "Libya" },
  { key: "liechtenstein", label: "Liechtenstein" },
  { key: "lithuania", label: "Lithuania" },
  { key: "luxembourg", label: "Luxembourg" },
  { key: "madagascar", label: "Madagascar" },
  { key: "malawi", label: "Malawi" },
  { key: "malaysia", label: "Malaysia" },
  { key: "maldives", label: "Maldives" },
  { key: "mali", label: "Mali" },
  { key: "malta", label: "Malta" },
  { key: "marshall islands", label: "Marshall Islands" },
  { key: "mauritania", label: "Mauritania" },
  { key: "mauritius", label: "Mauritius" },
  { key: "mexico", label: "Mexico" },
  { key: "micronesia", label: "Micronesia" },
  { key: "moldova", label: "Moldova" },
  { key: "monaco", label: "Monaco" },
  { key: "mongolia", label: "Mongolia" },
  { key: "montenegro", label: "Montenegro" },
  { key: "morocco", label: "Morocco" },
  { key: "mozambique", label: "Mozambique" },
  { key: "myanmar (burma)", label: "Myanmar (Burma)" },
  { key: "namibia", label: "Namibia" },
  { key: "nauru", label: "Nauru" },
  { key: "nepal", label: "Nepal" },
  { key: "netherlands", label: "Netherlands" },
  { key: "new zealand", label: "New Zealand" },
  { key: "nicaragua", label: "Nicaragua" },
  { key: "niger", label: "Niger" },
  { key: "nigeria", label: "Nigeria" },
  { key: "north macedonia", label: "North Macedonia" },
  { key: "norway", label: "Norway" },
  { key: "oman", label: "Oman" },
  { key: "pakistan", label: "Pakistan" },
  { key: "palau", label: "Palau" },
  { key: "panama", label: "Panama" },
  { key: "papua new guinea", label: "Papua New Guinea" },
  { key: "paraguay", label: "Paraguay" },
  { key: "peru", label: "Peru" },
  { key: "philippines", label: "Philippines" },
  { key: "poland", label: "Poland" },
  { key: "portugal", label: "Portugal" },
  { key: "qatar", label: "Qatar" },
  { key: "romania", label: "Romania" },
  { key: "russia", label: "Russia" },
  { key: "rwanda", label: "Rwanda" },
  { key: "saint kitts and nevis", label: "Saint Kitts and Nevis" },
  { key: "saint lucia", label: "Saint Lucia" },
  {
    key: "saint vincent and the grenadines",
    label: "Saint Vincent and the Grenadines",
  },
  { key: "samoa", label: "Samoa" },
  { key: "san marino", label: "San Marino" },
  { key: "sao tome and principe", label: "Sao Tome and Principe" },
  { key: "saudi arabia", label: "Saudi Arabia" },
  { key: "senegal", label: "Senegal" },
  { key: "serbia", label: "Serbia" },
  { key: "seychelles", label: "Seychelles" },
  { key: "sierra leone", label: "Sierra Leone" },
  { key: "singapore", label: "Singapore" },
  { key: "slovakia", label: "Slovakia" },
  { key: "slovenia", label: "Slovenia" },
  { key: "solomon islands", label: "Solomon Islands" },
  { key: "somalia", label: "Somalia" },
  { key: "south africa", label: "South Africa" },
  { key: "south sudan", label: "South Sudan" },
  { key: "spain", label: "Spain" },
  { key: "sri lanka", label: "Sri Lanka" },
  { key: "sudan", label: "Sudan" },
  { key: "suriname", label: "Suriname" },
  { key: "sweden", label: "Sweden" },
  { key: "switzerland", label: "Switzerland" },
  { key: "syria", label: "Syria" },
  { key: "taiwan", label: "Taiwan" },
  { key: "tajikistan", label: "Tajikistan" },
  { key: "tanzania", label: "Tanzania" },
  { key: "thailand", label: "Thailand" },
  { key: "togo", label: "Togo" },
  { key: "tonga", label: "Tonga" },
  { key: "trinidad and tobago", label: "Trinidad and Tobago" },
  { key: "tunisia", label: "Tunisia" },
  { key: "turkey", label: "Turkey" },
  { key: "turkmenistan", label: "Turkmenistan" },
  { key: "tuvalu", label: "Tuvalu" },
  { key: "uganda", label: "Uganda" },
  { key: "ukraine", label: "Ukraine" },
  { key: "united arab emirates", label: "United Arab Emirates" },
  { key: "united kingdom", label: "United Kingdom" },
  { key: "united states", label: "United States" },
  { key: "uruguay", label: "Uruguay" },
  { key: "uzbekistan", label: "Uzbekistan" },
  { key: "vanuatu", label: "Vanuatu" },
  { key: "vatican city", label: "Vatican City" },
  { key: "venezuela", label: "Venezuela" },
  { key: "vietnam", label: "Vietnam" },
  { key: "yemen", label: "Yemen" },
  { key: "zambia", label: "Zambia" },
  { key: "zimbabwe", label: "Zimbabwe" },
];
